# This is a comment in YAML

app:
  name: MyApp
  version: 1.0.0
  debug: true

server:
  host: localhost
  port: 8080

database:
  type: mysql
  host: 127.0.0.1
  port: 3306
  username: root
  password: secret

features:
  - login
  - register
  - reset_password
